//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docgia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Docgia()
        {
            this.Muontras = new HashSet<Muontra>();
        }
    
        public string sothe { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string email { get; set; }
        public string donvi { get; set; }
        public string chucvu { get; set; }
        public string anh { get; set; }
        public Nullable<System.DateTime> ngaycapthe { get; set; }
        public Nullable<System.DateTime> hanthe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Muontra> Muontras { get; set; }
    }
}
