//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muontra
    {
        public string sothutu { get; set; }
        public string sothema { get; set; }
        public string sachma { get; set; }
        public string thuthuma { get; set; }
        public Nullable<System.DateTime> ngaymuon { get; set; }
        public Nullable<System.DateTime> ngaytra { get; set; }
        public Nullable<System.DateTime> ngayphaitra { get; set; }
        public string tinhtrangmuon { get; set; }
        public string tinhtrangtra { get; set; }
        public Nullable<int> soluongmuon { get; set; }
        public Nullable<int> soluongtra { get; set; }
    
        public virtual Docgia Docgia { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual Thuthu Thuthu { get; set; }
    }
}
