//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.Dangkycabiets = new HashSet<Dangkycabiet>();
            this.Muontras = new HashSet<Muontra>();
        }
    
        public string ma { get; set; }
        public string ten { get; set; }
        public string tacgia { get; set; }
        public string loaisach { get; set; }
        public string nhaxuatbanma { get; set; }
        public Nullable<int> sotrang { get; set; }
        public Nullable<int> solanxuatban { get; set; }
        public Nullable<int> soluong { get; set; }
        public string noidung { get; set; }
        public string giatien { get; set; }
        public string ngonngu { get; set; }
        public string khoma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dangkycabiet> Dangkycabiets { get; set; }
        public virtual Khosach Khosach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Muontra> Muontras { get; set; }
        public virtual Nhaxuatban Nhaxuatban { get; set; }
    }
}
