//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuthu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thuthu()
        {
            this.Muontras = new HashSet<Muontra>();
        }
    
        public string ma { get; set; }
        public string ten { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
        public string chucvu { get; set; }
        public string email { get; set; }
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Muontra> Muontras { get; set; }
    }
}
